#!/bin/sh

killall MonitorControl
# killall TinkerTool
killall Übersicht
# open -a /Applications/Setapp/Bartender.app
open -a /Applications/Magnet.app
#open -a /Applications/Setapp/BetterTouchTool.app
brew services start yabai && yabai -m config layout float
