#! /bin/bash

xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Tools
brew install starship neofetch lolcat rg fd fzf exa pipx zoxide

# Terminal emulator
brew install --cask kitty
brew install koekeishiya/formulae/yabai
brew install koekeishiya/formulae/skhd

# Fonts
brew tap homebrew/cask-fonts
brew install font-jetbrains-mono font-fira-code-nerd-font

# Languages
brew install deno node go

# Libraries
pip install black colorpedia

brew install neovim
